version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependency
  versioning-strategy: increase
  commit-message:
    prefix: Build
    include: scope
